#!/bin/bash

# Define command-line arguments

function help() {
    echo
    echo "Usage: kubectl kubeplugin [nodes|pods] <NAMESPACE>"
    echo
    echo "Global options:"
    echo -e "\t-h, --help\t\t\tprint usage"
    echo
}

if [ $# -eq 0 ]; then
  echo "Error: no arguments are specified"
  help
  exit 1
fi

RESOURCE_TYPE="${1}"
NAMESPACE="${2}"

if [[ "${RESOURCE_TYPE}" != "node" && "${RESOURCE_TYPE}" != "pod" ]]; then
  echo "Error: unsupported resource type ${RESOURCE_TYPE}"
  help
  exit 1
fi

if [ "${NAMESPACE}" == "" ]; then
  echo "Error: namespace is a mandatory argument"
  help
  exit 1
fi

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  printf "%-10s %-12s %-50s %-12s %-12s\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
done